# Generated by Django 5.2.1 on 2025-05-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plazos',
            name='tipo_caso',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
