# Generated by Django 5.2.1 on 2025-05-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_plazos_tipo_caso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carga',
            old_name='fecha_conclusion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='carga',
            name='fecha_ingreso',
        ),
    ]
