# Generated by Django 5.2.1 on 2025-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_rename_fecha_conclusion_carga_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaDelito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=256)),
                ('cantidad', models.IntegerField(default=0)),
                ('mes', models.CharField(max_length=256)),
            ],
        ),
    ]
