# Generated by Django 5.2.1 on 2025-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_materiadelito'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiadelito',
            name='dependencia',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
