# Generated by Django 5.2.1 on 2025-05-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_materiadelito_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargatotal',
            name='nombre_fiscal',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
