# Generated by Django 5.2.1 on 2025-06-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_cargatotal_nombre_fiscal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargatotal',
            old_name='total_archivo_califica',
            new_name='asignados',
        ),
        migrations.RenameField(
            model_name='cargatotal',
            old_name='total_archivo_preliminar',
            new_name='calificados',
        ),
        migrations.RenameField(
            model_name='cargatotal',
            old_name='total_archivos_consentidos',
            new_name='etapa_intermedia',
        ),
        migrations.RenameField(
            model_name='cargatotal',
            old_name='total_casos_en_tramite',
            new_name='etapa_juzgamiento',
        ),
        migrations.RenameField(
            model_name='cargatotal',
            old_name='total_casos_ingresados',
            new_name='investigacion_pnp',
        ),
        migrations.RenameField(
            model_name='cargatotal',
            old_name='total_casos_resueltos',
            new_name='investigacion_preparatoria',
        ),
        migrations.RenameField(
            model_name='cargatotal',
            old_name='total_sentencias',
            new_name='pendientes',
        ),
        migrations.RemoveField(
            model_name='cargatotal',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='cargatotal',
            name='preliminares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargatotal',
            name='total_tramite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargatotal',
            name='tramite_historico',
            field=models.IntegerField(default=0),
        ),
    ]
