# Generated by Django 5.2.1 on 2025-06-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0007_rename_total_archivo_califica_cargatotal_asignados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramitesMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=256)),
                ('nombre_fiscal', models.CharField(max_length=256)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_conclusion', models.DateField(blank=True, null=True)),
                ('mes', models.CharField(max_length=256)),
                ('total_tramite', models.IntegerField(default=0)),
                ('tramite_mes', models.IntegerField(default=0)),
                ('resuelto_mes', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
