# Generated by Django 5.2.1 on 2025-06-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0009_remove_tramitesmensual_fecha_conclusion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaSiatf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
                ('especialidad', models.CharField(max_length=256)),
                ('casos_ingresados', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
