# Generated by Django 5.2.1 on 2025-06-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0010_cargasiatf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlazosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=256)),
                ('nombre_fiscal', models.CharField(max_length=256)),
                ('etapa', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
                ('dentro_plazo', models.IntegerField(default=0)),
                ('por_vencer', models.IntegerField(default=0)),
                ('vencidos', models.IntegerField(default=0)),
            ],
        ),
    ]
