# Generated by Django 5.2.1 on 2025-06-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0011_plazosdetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaAnio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=256)),
                ('nombre_fiscal', models.CharField(max_length=256)),
                ('resueltos', models.IntegerField(default=0)),
                ('tramites', models.IntegerField(default=0)),
                ('ingresados', models.IntegerField(default=0)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
